In [1]:
import pandas as pd
from datetime import timedelta, datetime
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")
import acquire
from acquire import get_stores_df
from acquire import get_combined_df

In [2]:
sales_df = acquire.get_sales_df()
sales_df.head()

item  sale_amount                      sale_date  sale_id  store
0     1         33.0  Sat, 10 Sep 2016 00:00:00 GMT     5001      3
1     1         27.0  Sun, 11 Sep 2016 00:00:00 GMT     5002      3
2     1         26.0  Mon, 12 Sep 2016 00:00:00 GMT     5003      3
3     1         22.0  Tue, 13 Sep 2016 00:00:00 GMT     5004      3
4     1         25.0  Wed, 14 Sep 2016 00:00:00 GMT     5005      3

In [3]:
sales_df.item.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [4]:
df = get_stores_df()
df.head(3)

store_address   store_city  store_id store_state  store_zipcode
0   12125 Alamo Ranch Pkwy  San Antonio         1          TX          78253
1         9255 FM 471 West  San Antonio         2          TX          78251
2  2118 Fredericksburg Rdj  San Antonio         3          TX          78201

In [5]:
df = acquire.get_combined_df()
df.sample(20)


item_brand  item_id  \
26126        Betty Crocker       22   
138652        Usda Produce       28   
144573        Usda Produce       28   
234346     The First Years       33   
508467                Dove       48   
346343            Munchies       39   
143276        Usda Produce       28   
74197                 Hood       25   
239591               Halls       34   
42459                Reese       23   
432589              Elmers       44   
31910        Betty Crocker       22   
174046             Petmate       30   
531249              Choice       50   
406053             Ferrara       43   
177374             Petmate       30   
469918          Mama Marys       46   
390642  Moms Best Naturals       42   
121666              Morton       27   
495800                Dove       48   

                                                item_name  item_price  \
26126   Betty Crocker Twin Pack Real Potatoes Scallope...        7.31   
138652                                              Guava        7.52   
144573                                              Guava        7.52   
234346  Tomy The First Years Gumdrop Orthodontic Pacif...        6.52   
508467  Dove Men + Care Antiperspirant Deodorant Cool ...        3.72   
346343  Munchies Sandwich Crackers Cheddar Cheese On G...        9.02   
143276                                              Guava        7.52   
74197          Hood Latte Iced Coffee Drink Vanilla Latte        2.43   
239591  Halls Menthol Cough Suppresant/oral Anesthetic...        4.17   
42459      Reese Mandarin Oranges Segments In Light Syrup        1.78   
432589                Elmers Board Mate Dual Tip Glue Pen        7.06   
31910   Betty Crocker Twin Pack Real Potatoes Scallope...        7.31   
174046  Petmate Booda Bones Steak Bacon & Chicken Flav...        8.39   
531249  Choice Organic Teas Black Tea Classic Black - ...        5.20   
406053                              Ferrara Vanilla Syrup        8.40   
177374  Petmate Booda Bones Steak Bacon & Chicken Flav...        8.39   
469918                                        Pizza Sauce        4.65   
390642  Moms Best Naturals Cereal Toasted Cinnamon Squ...        2.97   
121666                          Morton Kosher Salt Coarse        6.01   
495800  Dove Men + Care Antiperspirant Deodorant Cool ...        3.72   

          item_upc12    item_upc14  item  sale_amount  \
26126    16000288829   16000288829    22         76.0   
138652  719175900007  719175900007    28         80.0   
144573  719175900007  719175900007    28        110.0   
234346   71463060078   71463060078    33         74.0   
508467   79400271631   79400271631    48         49.0   
346343   28400029254   28400029254    39         56.0   
143276  719175900007  719175900007    28        108.0   
74197    44100117428   44100117428    25         70.0   
239591  312546628694  312546628694    34         16.0   
42459    70670009658   70670009658    23         26.0   
432589   26000001403   26000001403    44         26.0   
31910    16000288829   16000288829    22        101.0   
174046  723503568678  723503568678    30         33.0   
531249   47445919221   47445919221    50         59.0   
406053   71403000379   71403000379    43         69.0   
177374  723503568678  723503568678    30         42.0   
469918   35457770664   35457770664    46         66.0   
390642  883978129115  883978129115    42         45.0   
121666   24600017008   24600017008    27          7.0   
495800   79400271631   79400271631    48         90.0   

                            sale_date  sale_id  store  \
26126   Thu, 17 Jul 2014 00:00:00 GMT   391327      5   
138652  Wed, 30 Aug 2017 00:00:00 GMT   503853      6   
144573  Sat, 16 Nov 2013 00:00:00 GMT   509774     10   
234346  Thu, 11 Sep 2014 00:00:00 GMT   599547      9   
508467  Mon, 20 Apr 2015 00:00:00 GMT   873668      9   
346343  Sat, 14 May 2016 00:00:00 GMT   711544     10   
143276  Wed, 29 Apr 2015 00:00:00 GMT   508477      9   
74197   

In [6]:
df.columns

Index(['item_brand', 'item_id', 'item_name', 'item_price', 'item_upc12',
       'item_upc14', 'item', 'sale_amount', 'sale_date', 'sale_id', 'store',
       'store_address', 'store_city', 'store_id', 'store_state',
       'store_zipcode'],
      dtype='object')

In [7]:
df.shape[0]

547800

In [8]:
df.isnull().sum()

item_brand       0
item_id          0
item_name        0
item_price       0
item_upc12       0
item_upc14       0
item             0
sale_amount      0
sale_date        0
sale_id          0
store            0
store_address    0
store_city       0
store_id         0
store_state      0
store_zipcode    0
dtype: int64

In [9]:
df.store_id.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
df.item.unique()

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [11]:
df.sale_date.unique()

array(['Tue, 01 Jan 2013 00:00:00 GMT', 'Wed, 02 Jan 2013 00:00:00 GMT',
       'Thu, 03 Jan 2013 00:00:00 GMT', ...,
       'Fri, 29 Dec 2017 00:00:00 GMT', 'Sat, 30 Dec 2017 00:00:00 GMT',
       'Sun, 31 Dec 2017 00:00:00 GMT'], dtype=object)

In [14]:
## Set datetime index
## reassign the sale_date column to be a datetime type
df.sale_date = pd.to_datetime(df.sale_date)
## set the index as that date and then sort index (by the date)
df = df.set_index('sale_date').sort_index()
df.index.strftime('%d-%m-%Y')

Index(['01-01-2013', '01-01-2013', '01-01-2013', '01-01-2013', '01-01-2013',
       '01-01-2013', '01-01-2013', '01-01-2013', '01-01-2013', '01-01-2013',
       ...
       '31-12-2017', '31-12-2017', '31-12-2017', '31-12-2017', '31-12-2017',
       '31-12-2017', '31-12-2017', '31-12-2017', '31-12-2017', '31-12-2017'],
      dtype='object', name='sale_date', length=547800)

In [ ]:
df = df.drop(columns='item')
df.head()

In [ ]:
df.shape[0]

## Refresher notes on data prep with time series:
- look for gaps in the data
- set date-tme index
- look at just one variable changing over time
- this is univariate analysis
- look for null values

## Exercises

In [ ]:
# 2. Plot the distribution of sale_amount and item_price.

by_date_sales = df.groupby(['sale_date']).sale_amount.sum().reset_index()
by_date_sales.plot(x='sale_date', y='sale_amount')

In [ ]:
df.sale_amount.hist()

In [ ]:
df.item_price.hist()

In [ ]:
by_date_price = df.groupby(['sale_date']).item_price.sum().reset_index()
by_date_price.plot(x='sale_date', y='item_price')

In [ ]:
# observations per store = item transactions per store
# is each store equaly represented? >> check store ids
df.store_id.value_counts()

In [ ]:
# is each item equally represented? >> check item_ids
df.item_id.value_counts().sort_index()

In [ ]:
# finding the first sale
first_sale = df.reset_index().groupby(['store_id', 'item_id']).sale_date.min()
first_sale.head()

In [ ]:
# unique item first sales:
first_sale.unique()

In [ ]:
# get the last sale
last_sale = df.reset_index().groupby(['store_id', 'item_id']).sale_date.max()
last_sale.head()

In [ ]:
last_sale.unique()

In [ ]:
# how many different days was each item sold at each store:
days_per_store_per_item = df.reset_index().groupby(['store_id', 'item_id']).sale_date.nunique()
days_per_store_per_item.head()

In [ ]:
days_per_store_per_item.unique()

In [ ]:
# Check for gaps in the data:
print("The number of rows is", df.index.nunique())
n_days = df.index.max() - df.index.min() + pd.Timedelta('1d')
print("Number of days between first and last day is ", n_days)

In [ ]:
# 3. Set the index to be the datetime variable.

df.head()

In [ ]:
# 4. Add a 'month' and 'day of week' column to your dataframe.
# 5. Add a column to your dataframe, sales_total, which is a derived from sale_amount 
# (total items) and item_price.
df['month'] = df.index.strftime('%b')
df['weekday'] = df.index.strftime('%a')
df['sales_total'] = df.sale_amount * df.item_price
df.head()

In [23]:
# 6. Make sure all the work that you have done above is reproducible. That is, you should put the code above into separate functions 
# and be able to re-run the functions and get the same results.

import pandas as pd
import acquire
import os
import requests

def prepare_stores():
    df = acquire.get_combined_df()
    # set the DTG column
    df.sale_date = pd.to_datetime(df.sale_date)
    # set the DTG columns as index, and sort by index
    df = df.set_index('sale_date').sort_index()
    # print check statements for df shape, and item sales dates
    print("The number of unique days is", df.index.nunique())
    n_days = df.index.max() - df.index.min() + pd.Timedelta('1d')
    print("Number of days between first and last day is ", n_days)
    df['month'] = df.index.strftime('%b')
    df['weekday'] = df.index.strftime('%a')
    df['sales_total'] = df.sale_amount * df.item_price
    df = df.drop(columns=['store_id', 'item'])
    return df

In [24]:
df = prepare_stores()
df.head()

The number of rows is 1826
Number of days between first and last day is  1826 days 00:00:00


item_brand  item_id  \
sale_date                                                    
2013-01-01 00:00:00+00:00            Doctors Best       21   
2013-01-01 00:00:00+00:00                    Hood       25   
2013-01-01 00:00:00+00:00  Deerfields Gluten Free       36   
2013-01-01 00:00:00+00:00                    Dove       48   
2013-01-01 00:00:00+00:00               Triaminic       26   

                                                                   item_name  \
sale_date                                                                      
2013-01-01 00:00:00+00:00  Doctors Best Best Curcumin C3 Complex 1000mg T...   
2013-01-01 00:00:00+00:00         Hood Latte Iced Coffee Drink Vanilla Latte   
2013-01-01 00:00:00+00:00           Rice Bran Gluten Free Dinner Rolls Plain   
2013-01-01 00:00:00+00:00  Dove Men + Care Antiperspirant Deodorant Cool ...   
2013-01-01 00:00:00+00:00  Triaminic Syrup Night Time Cold & Cough Grape 4oz   

                           item_price    item_upc12    item_upc14  \
sale_date                                                           
2013-01-01 00:00:00+00:00        8.09  753950001954  753950001954   
2013-01-01 00:00:00+00:00        2.43   44100117428   44100117428   
2013-01-01 00:00:00+00:00        7.95  610358991525  610358991525   
2013-01-01 00:00:00+00:00        3.72   79400271631   79400271631   
2013-01-01 00:00:00+00:00        0.98  300436344045  300436344045   

                           sale_amount  sale_id  store  \
sale_date                                                
2013-01-01 00:00:00+00:00         22.0   365201      1   
2013-01-01 00:00:00+00:00         45.0   452849      9   
2013-01-01 00:00:00+00:00         55.0   655535     10   
2013-01-01 00:00:00+00:00         45.0   860047      2   
2013-01-01 00:00:00+00:00         19.0   463805      5   

                                    store_address   store_city store_state  \
sale_date                                                                    
2013-01-01 00:00:00+00:00  12125 Alamo Ranch Pkwy  San Antonio          TX   
2013-01-01 00:00:00+00:00      735 SW Military Dr  San Antonio          TX   
2013-01-01 00:00:00+00:00    8503 NW Military Hwy  San Antonio          TX   
2013-01-01 00:00:00+00:00        9255 FM 471 West  San Antonio          TX   
2013-01-01 00:00:00+00:00         1520 Austin Hwy  San Antonio          TX   

                           store_zipcode month weekday  sales_total  
sale_date                                                            
2013-01-01 00:00:00+00:00          78253   Jan     Tue       177.98  
2013-01-01 00:00:00+00:00          78221   Jan     Tue       109.35  
2013-01-01 00:00:00+00:00          78231   Jan     Tue       437.25  
2013-01-01 00:00:00+00:00          78251   Jan     Tue       167.40  
2013-01-01 00:00:00+00:00          78218   Jan     Tue        18.62