In [1]:
import pandas as pd
from datetime import timedelta, datetime
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")
import acquire
from acquire import get_stores_df
from acquire import get_combined_df

In [2]:
sales_df = acquire.get_sales_df()
sales_df.head()

item  sale_amount                      sale_date  sale_id  store
0     1         33.0  Sat, 10 Sep 2016 00:00:00 GMT     5001      3
1     1         27.0  Sun, 11 Sep 2016 00:00:00 GMT     5002      3
2     1         26.0  Mon, 12 Sep 2016 00:00:00 GMT     5003      3
3     1         22.0  Tue, 13 Sep 2016 00:00:00 GMT     5004      3
4     1         25.0  Wed, 14 Sep 2016 00:00:00 GMT     5005      3

In [3]:
sales_df.item.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [4]:
df = get_stores_df()
df.head(3)

store_address   store_city  store_id store_state  store_zipcode
0   12125 Alamo Ranch Pkwy  San Antonio         1          TX          78253
1         9255 FM 471 West  San Antonio         2          TX          78251
2  2118 Fredericksburg Rdj  San Antonio         3          TX          78201

In [5]:
df = acquire.get_combined_df()
df.sample(20)


item_brand  item_id  \
343790         Munchies       39   
438057           Elmers       44   
516356         Easy-off       49   
158681            Heinz       29   
537873           Choice       50   
218184         Barefoot       32   
508147             Dove       48   
420192           Elmers       44   
18288     Betty Crocker       22   
65295      Smart Living       24   
434403           Elmers       44   
9598       Doctors Best       21   
1483       Doctors Best       21   
10337      Doctors Best       21   
225649  The First Years       33   
403693          Ferrara       43   
30120     Betty Crocker       22   
432847           Elmers       44   
121688           Morton       27   
225853  The First Years       33   

                                                item_name  item_price  \
343790  Munchies Sandwich Crackers Cheddar Cheese On G...        9.02   
438057                Elmers Board Mate Dual Tip Glue Pen        7.06   
516356                  Easy-off Oven Cleaner Lemon Scent        9.54   
158681                        Heinz Tomato Ketchup - 2 Ct        8.65   
537873  Choice Organic Teas Black Tea Classic Black - ...        5.20   
218184                         Barefoot Pinot Grigio  187        0.68   
508147  Dove Men + Care Antiperspirant Deodorant Cool ...        3.72   
420192                Elmers Board Mate Dual Tip Glue Pen        7.06   
18288   Betty Crocker Twin Pack Real Potatoes Scallope...        7.31   
65295                 Smart Living Charcoal Lighter Fluid        5.34   
434403                Elmers Board Mate Dual Tip Glue Pen        7.06   
9598    Doctors Best Best Curcumin C3 Complex 1000mg T...        8.09   
1483    Doctors Best Best Curcumin C3 Complex 1000mg T...        8.09   
10337   Doctors Best Best Curcumin C3 Complex 1000mg T...        8.09   
225649  Tomy The First Years Gumdrop Orthodontic Pacif...        6.52   
403693                              Ferrara Vanilla Syrup        8.40   
30120   Betty Crocker Twin Pack Real Potatoes Scallope...        7.31   
432847                Elmers Board Mate Dual Tip Glue Pen        7.06   
121688                          Morton Kosher Salt Coarse        6.01   
225853  Tomy The First Years Gumdrop Orthodontic Pacif...        6.52   

          item_upc12    item_upc14  item  sale_amount  \
343790   28400029254   28400029254    39         61.0   
438057   26000001403   26000001403    44         44.0   
516356   62338879772   62338879772    49         40.0   
158681   13000001038   13000001038    29         81.0   
537873   47445919221   47445919221    50         44.0   
218184    8500004528    8500004528    32         65.0   
508147   79400271631   79400271631    48         58.0   
420192   26000001403   26000001403    44         33.0   
18288    16000288829   16000288829    22         41.0   
65295   688267084225  688267084225    24         35.0   
434403   26000001403   26000001403    44         53.0   
9598    753950001954  753950001954    21         31.0   
1483    753950001954  753950001954    21         17.0   
10337   753950001954  753950001954    21         50.0   
225649   71463060078   71463060078    33         68.0   
403693   71403000379   71403000379    43         67.0   
30120    16000288829   16000288829    22         57.0   
432847   26000001403   26000001403    44         25.0   
121688   24600017008   24600017008    27         13.0   
225853   71463060078   71463060078    33         68.0   

                            sale_date  sale_id  store  \
343790  Sun, 18 May 2014 00:00:00 GMT   708991      9   
438057  Sun, 02 Jul 2017 00:00:00 GMT   803258     10   
516356  Fri, 25 Nov 2016 00:00:00 GMT   881557      3   
158681  Tue, 04 Jul 2017 00:00:00 GMT   523882      7   
537873  Tue, 27 Oct 2015 00:00:00 GMT   903074      5   
218184  Wed, 10 Jun 2015 00:00:00 GMT   583385     10   
508147  Wed, 04 Jun 2014 00:00:00 GMT   873348      9   
420192  Thu, 01 Aug 2013 00:00:00 GMT   785393      1   
18288   Tue

In [6]:
df.columns

Index(['item_brand', 'item_id', 'item_name', 'item_price', 'item_upc12',
       'item_upc14', 'item', 'sale_amount', 'sale_date', 'sale_id', 'store',
       'store_address', 'store_city', 'store_id', 'store_state',
       'store_zipcode'],
      dtype='object')

In [7]:
df.shape[0]

547800

In [8]:
df.isnull().sum()

item_brand       0
item_id          0
item_name        0
item_price       0
item_upc12       0
item_upc14       0
item             0
sale_amount      0
sale_date        0
sale_id          0
store            0
store_address    0
store_city       0
store_id         0
store_state      0
store_zipcode    0
dtype: int64

In [9]:
df.store_id.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
df.item.unique()

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [11]:
df.sale_date.unique()

array(['Tue, 01 Jan 2013 00:00:00 GMT', 'Wed, 02 Jan 2013 00:00:00 GMT',
       'Thu, 03 Jan 2013 00:00:00 GMT', ...,
       'Fri, 29 Dec 2017 00:00:00 GMT', 'Sat, 30 Dec 2017 00:00:00 GMT',
       'Sun, 31 Dec 2017 00:00:00 GMT'], dtype=object)

In [12]:
## Set datetime index
## reassign the sale_date column to be a datetime type
df.sale_date = pd.to_datetime(df.sale_date, format = '%a, %d %b %Y %H:%M:%S %Z')
## set the index as that date and then sort index (by the date)
df = df.set_index('sale_date').sort_index()

In [13]:
df.head()

item_brand  item_id  \
sale_date                                                    
2013-01-01 00:00:00+00:00            Doctors Best       21   
2013-01-01 00:00:00+00:00                    Hood       25   
2013-01-01 00:00:00+00:00  Deerfields Gluten Free       36   
2013-01-01 00:00:00+00:00                    Dove       48   
2013-01-01 00:00:00+00:00               Triaminic       26   

                                                                   item_name  \
sale_date                                                                      
2013-01-01 00:00:00+00:00  Doctors Best Best Curcumin C3 Complex 1000mg T...   
2013-01-01 00:00:00+00:00         Hood Latte Iced Coffee Drink Vanilla Latte   
2013-01-01 00:00:00+00:00           Rice Bran Gluten Free Dinner Rolls Plain   
2013-01-01 00:00:00+00:00  Dove Men + Care Antiperspirant Deodorant Cool ...   
2013-01-01 00:00:00+00:00  Triaminic Syrup Night Time Cold & Cough Grape 4oz   

                           item_price    item_upc12    item_upc14  item  \
sale_date                                                                 
2013-01-01 00:00:00+00:00        8.09  753950001954  753950001954    21   
2013-01-01 00:00:00+00:00        2.43   44100117428   44100117428    25   
2013-01-01 00:00:00+00:00        7.95  610358991525  610358991525    36   
2013-01-01 00:00:00+00:00        3.72   79400271631   79400271631    48   
2013-01-01 00:00:00+00:00        0.98  300436344045  300436344045    26   

                           sale_amount  sale_id  store  \
sale_date                                                
2013-01-01 00:00:00+00:00         22.0   365201      1   
2013-01-01 00:00:00+00:00         45.0   452849      9   
2013-01-01 00:00:00+00:00         55.0   655535     10   
2013-01-01 00:00:00+00:00         45.0   860047      2   
2013-01-01 00:00:00+00:00         19.0   463805      5   

                                    store_address   store_city  store_id  \
sale_date                                                                  
2013-01-01 00:00:00+00:00  12125 Alamo Ranch Pkwy  San Antonio         1   
2013-01-01 00:00:00+00:00      735 SW Military Dr  San Antonio         9   
2013-01-01 00:00:00+00:00    8503 NW Military Hwy  San Antonio        10   
2013-01-01 00:00:00+00:00        9255 FM 471 West  San Antonio         2   
2013-01-01 00:00:00+00:00         1520 Austin Hwy  San Antonio         5   

                          store_state  store_zipcode  
sale_date                                             
2013-01-01 00:00:00+00:00          TX          78253  
2013-01-01 00:00:00+00:00          TX          78221  
2013-01-01 00:00:00+00:00          TX          78231  
2013-01-01 00:00:00+00:00          TX          78251  
2013-01-01 00:00:00+00:00          TX          78218